version: '2'

services:
  web:
    build:
      context: ./containers/
      dockerfile: web.docker
    volumes:
      - ./:/var/www
    ports:
      - "8080:80"
    links:
      - app
  app:
    build:
      context: ./containers/
      dockerfile: app.docker
    volumes:
      - ./:/var/www
    ports:
      - "9000"
    links:
      - db
      - redis
  db:
    image: mariadb:10.1
    environment:
      MYSQL_DATABASE: webapp
      MYSQL_USER: webapp
      MYSQL_PASSWORD: P@ssW0rd
      MYSQL_ROOT_PASSWORD: P@ssW0rd
    ports:
      - "3306"
  redis:
    image: redis:3.2-alpine
    ports:
      - "6379"
